version: '3.8'

services:
  app:
    image: ${DOCKER_USERNAME}/photoommit:latest
    container_name: photoommit
    restart: always
    ports:
      - "3003:3000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs 