name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
    paths:
      - 'frontend/**'
      - 'backend/**'
      - 'Dockerfile'
      - 'docker-compose.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'frontend/**'
      - 'backend/**'
      - 'Dockerfile'
      - 'docker-compose.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: DOCKER_HUB_USERNAME

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Cache npm dependencies
      uses: actions/cache@v3
      with:
        path: |
          frontend/node_modules
          backend/node_modules
        key: ${{ runner.os }}-modules-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-modules-

    - name: Install Dependencies
      run: |
        cd frontend && npm install
        cd ../backend && npm install

    - name: Build
      run: |
        cd frontend && npm run build
        cd ../backend && npm run build

    - name: Set up Docker Buildx
      if: github.event_name == 'push'
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      if: github.event_name == 'push'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and Push Docker image
      if: github.event_name == 'push'
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/photoommit:latest
        secrets: |
          "OSS_ACCESS_KEY_ID=${{ secrets.OSS_ACCESS_KEY_ID }}"
          "OSS_ACCESS_KEY_SECRET=${{ secrets.OSS_ACCESS_KEY_SECRET }}"
          "OSS_BUCKET=${{ secrets.OSS_BUCKET }}"
          "OSS_REGION=${{ secrets.OSS_REGION }}"
          "OSS_ENDPOINT=${{ secrets.OSS_ENDPOINT }}"

    - name: Deploy to Server
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /opt/photoommit
          # 创建 docker-compose.yml
          cat > docker-compose.yml << EOL
          version: '3'
          services:
            app:
              image: ${{ secrets.DOCKER_HUB_USERNAME }}/photoommit:latest
              ports:
                - "8087:3000"
              environment:
                - NODE_ENV=production
              volumes:
                - ./.env:/app/backend/.env
              restart: always
          EOL
          # 创建 .env 文件
          echo "OSS_ACCESS_KEY_ID=${{ secrets.OSS_ACCESS_KEY_ID }}" > .env
          echo "OSS_ACCESS_KEY_SECRET=${{ secrets.OSS_ACCESS_KEY_SECRET }}" >> .env
          echo "OSS_BUCKET=${{ secrets.OSS_BUCKET }}" >> .env
          echo "OSS_REGION=${{ secrets.OSS_REGION }}" >> .env
          echo "OSS_ENDPOINT=${{ secrets.OSS_ENDPOINT }}" >> .env
          # 拉取镜像并启动服务
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/photoommit:latest
          docker-compose down
          docker-compose up -d 