name: MCP Build and Test

on:
  push:
    branches: [ master ]
    paths:
      - 'mcp/**'
      - '.github/workflows/mcp-build.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'mcp/**'
      - '.github/workflows/mcp-build.yml'
  workflow_dispatch: # 允许手动触发

jobs:
  build-mcp:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'mcp/package-lock.json'

    - name: Install MCP dependencies
      working-directory: ./mcp
      run: npm ci

    - name: Build MCP project
      working-directory: ./mcp
      run: npm run build

    - name: Verify build output
      working-directory: ./mcp
      run: |
        echo "Checking build output..."
        ls -la build/
        if [ -f "build/index.js" ]; then
          echo "✅ MCP build successful - index.js exists"
        else
          echo "❌ MCP build failed - index.js not found"
          exit 1
        fi

    - name: Test MCP executable permissions
      working-directory: ./mcp
      run: |
        if [ -x "build/index.js" ]; then
          echo "✅ MCP executable has correct permissions"
        else
          echo "❌ MCP executable missing execute permissions"
          exit 1
        fi

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: mcp-build-${{ github.run_number }}
        path: mcp/build/
        retention-days: 30 