name: MCP Build, Test and Publish

on:
  push:
    branches: [ master ]
    paths:
      - 'mcp/**'
      - '.github/workflows/mcp-build-and-publish.yml'
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]
    paths:
      - 'mcp/**'
      - '.github/workflows/mcp-build-and-publish.yml'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 1.0.0)'
        required: false
        default: ''
      publish:
        description: 'Publish to npm after build'
        required: false
        default: false
        type: boolean

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'mcp/package-lock.json'
      - name: Install dependencies
        working-directory: ./mcp
        run: npm ci
      - name: Build MCP
        working-directory: ./mcp
        run: npm run build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mcp-build-${{ github.run_number }}
          path: mcp/build/
          retention-days: 30

  publish:
    needs: build-and-test
    if: |
      (github.event_name == 'push' && (github.ref_type == 'tag' || github.event.inputs.publish == 'true'))
      || (github.event_name == 'workflow_dispatch' && github.event.inputs.publish == 'true')
    runs-on: ubuntu-latest
    environment: npm-publish
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'mcp/package-lock.json'
          registry-url: 'https://registry.npmjs.org'
          scope: '@tans-dev'
      - name: Install dependencies
        working-directory: ./mcp
        run: npm ci
      - name: Build MCP
        working-directory: ./mcp
        run: npm run build
      - name: Check tag and package.json version match
        if: startsWith(github.ref, 'refs/tags/')
        working-directory: ./mcp
        run: |
          TAG_VERSION="${GITHUB_REF#refs/tags/v}"
          PKG_VERSION=$(node -p "require('./package.json').version")
          if [ "$TAG_VERSION" != "$PKG_VERSION" ]; then
            echo "❌ Tag version and package.json version do not match!"
            exit 1
          fi
      - name: Publish to NPM
        working-directory: ./mcp
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: PhotoOmmit MCP ${{ github.ref_name }}
          body: |
            Automated release from GitHub Actions
            Version: ${{ github.ref_name }}
      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mcp-release-${{ github.ref_name }}
          path: mcp/build/
          retention-days: 90 